export const USER_SIGNIN_API = "USER_SIGNIN_API"; 


export const USLOGIN = "USLOGIN"; 

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA"; 

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
